name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-tagged:
    name: Build release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dashit
